---
gemName: "quake_timesheets_client"
gemHomepage: https://www.quake.co.uk
gemSummary: A client for the Quake Timesheets API
gemDescription: Requires the Quake Timesheets system
gemLicense: MIT
gemVersion: 0.1.2
gemRequiredRubyVersion: ">= 2.7"
library: faraday
moduleName: Quake::Timesheets
