=begin
#TimesheetsApi (params in:formData)

# <p>Another API description</p> 

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Quake::Timesheets::EntriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EntriesApi' do
  before do
    # run before each test
    @api_instance = Quake::Timesheets::EntriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EntriesApi' do
    it 'should create an instance of EntriesApi' do
      expect(@api_instance).to be_instance_of(Quake::Timesheets::EntriesApi)
    end
  end

  # unit tests for get_api_v1_entries
  # Search for entries matching filters
  # @param [Hash] opts the optional parameters
  # @option opts [String] :dataset_id Filter to the entries belonging to one of the identified datasets
  # @option opts [String] :person_id Filter to the entries belonging to one of the identified people
  # @option opts [String] :from_date Return only entries after this DateTime (inclusive)
  # @option opts [String] :to_date Return only entries before this DateTime (inclusive)
  # @return [Array<Entry>]
  describe 'get_api_v1_entries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_api_v1_entries
  # Create a new Entry
  # @param [Hash] opts the optional parameters
  # @option opts [String] :person_id ID of the person to which this entry pertains
  # @option opts [String] :start_at Time period at which this entry starts
  # @option opts [String] :end_at Time period at which this entry ends
  # @option opts [Float] :quantity 
  # @option opts [String] :unit 
  # @option opts [String] :external_reference Unique identifier of the activity this Entry relates to
  # @return [Entry]
  describe 'post_api_v1_entries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_api_v1_entries_id
  # Update an existing Entry
  # @param id The ID for the Entry
  # @param [Hash] opts the optional parameters
  # @option opts [String] :person_id ID of the person to which this entry pertains
  # @option opts [String] :start_at Time period at which this entry starts
  # @option opts [String] :end_at Time period at which this entry ends
  # @option opts [Float] :quantity 
  # @option opts [String] :unit 
  # @option opts [String] :external_reference Unique identifier of the activity this Entry relates to
  # @return [Entry]
  describe 'post_api_v1_entries_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
