=begin
#TimesheetsApi (params in:formData)

# <p>Another API description</p> 

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Quake::Timesheets::PeopleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PeopleApi' do
  before do
    # run before each test
    @api_instance = Quake::Timesheets::PeopleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PeopleApi' do
    it 'should create an instance of PeopleApi' do
      expect(@api_instance).to be_instance_of(Quake::Timesheets::PeopleApi)
    end
  end

  # unit tests for get_api_v1_people
  # Search for people matching filters
  # @param [Hash] opts the optional parameters
  # @option opts [String] :dataset_id Filter to the people belonging to one of the identified datasets
  # @return [Array<Person>]
  describe 'get_api_v1_people test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_api_v1_people
  # Create a new Person record
  # @param name Human readable name for the Person object (usually the subject&#39;s real name)
  # @param dataset_id Dataset to which the Person object should belong
  # @param [Hash] opts the optional parameters
  # @return [Person]
  describe 'post_api_v1_people test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
