=begin
#TimesheetsApi (params in:formData)

# <p>Another API description</p> 

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

# Pre-define base modules
'Quake::Timesheets'.split('::').reduce(Object) { |previous, mod| previous.const_set(mod.to_sym, Module.new) }

# Common files
require 'quake_timesheets_client/api_client'
require 'quake_timesheets_client/api_error'
require 'quake_timesheets_client/version'
require 'quake_timesheets_client/configuration'

# Models
require 'quake_timesheets_client/models/approval'
require 'quake_timesheets_client/models/approval_type'
require 'quake_timesheets_client/models/dataset'
require 'quake_timesheets_client/models/entry'
require 'quake_timesheets_client/models/person'

# APIs
require 'quake_timesheets_client/api/approval_types_api'
require 'quake_timesheets_client/api/approvals_api'
require 'quake_timesheets_client/api/datasets_api'
require 'quake_timesheets_client/api/entries_api'
require 'quake_timesheets_client/api/people_api'

module Quake::Timesheets
  class << self
    # Customize default settings for the SDK using block.
    #   Quake::Timesheets.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
